### ISSUE TITLE
Private Values In appsettings.json

### ISSUE THREAD

**Issue by TheHokieCoder** [JLewinski/dotnet-cas-client-with-core#2]
In your `DotnetCore` branch, in `dotnet-cas-client-with-core/CoreExample/appsettings.json` you have values that are custom to your setup at Auburn. Not that they are secrets, but you probably want to scrub those from this repository so people cloning don't try to hit your CAS server. 😄

**Comment by JLewinski** [comment]
Yeah, I was kinda just hoping nobody would notice after I made a commit to hide them... Oh well. I just took down that branch and published one without it.

**Comment by TheHokieCoder** [comment]
The new [branch](https://github.com/JLewinski/dotnet-cas-client-with-core/blob/Core/CoreExample/appsettings.json) still has those values in it. Not a big deal, like I said before, but Visual Studio pops up a warning because some of the `CasOptions` keys are repeated.
